### ISSUE TITLE
["Feature" Request] Prebuilt UF2s?

### ISSUE THREAD

**Issue by ReznorsRevenge1** [Kozova1/fusee-rp2040#1]
The title says it all, could you add some up-to-date prebuilt .UF2s to Releases? My suggestion would be to set up a workflow that auto-builds it for you.

**Comment by Kozova1** [comment]
This repo was mostly an experiment which I never could verify actually work, I haven't got to working on it in a while

**Comment by ReznorsRevenge1** [comment]
Oh ok. Are there any other projects like this one that you could recommend?

**Comment by Kozova1** [comment]
When I was working on this, I remember finding this, it might help you https://github.com/blockfeed/sam-fusee-launcher-internal

**Comment by ReznorsRevenge1** [comment]
Thanks, I'll check it out.
